//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Shared.Resources.UsersModules.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Shared.Resources.UsersModules.User.UsersMessages", typeof(UsersMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, user email is required.
        /// </summary>
        public static string errorEmailIsRequired {
            get {
                return ResourceManager.GetString("errorEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is required addded before.
        /// </summary>
        public static string errorPhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("errorPhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user contact email is already added.
        /// </summary>
        public static string errorUserContactEmailWasAdded {
            get {
                return ResourceManager.GetString("errorUserContactEmailWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user email is already added.
        /// </summary>
        public static string errorUserEmailWasAdded {
            get {
                return ResourceManager.GetString("errorUserEmailWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, user login name is required.
        /// </summary>
        public static string errorUserLoginNameIsRequired {
            get {
                return ResourceManager.GetString("errorUserLoginNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user login name is already added.
        /// </summary>
        public static string errorUserLoginNameWasAdded {
            get {
                return ResourceManager.GetString("errorUserLoginNameWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, username is required.
        /// </summary>
        public static string errorUsernameIsRequired {
            get {
                return ResourceManager.GetString("errorUsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is already added.
        /// </summary>
        public static string errorUsernameWasAdded {
            get {
                return ResourceManager.GetString("errorUsernameWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number was addded before.
        /// </summary>
        public static string errorUserPhoneNumberWasAdded {
            get {
                return ResourceManager.GetString("errorUserPhoneNumberWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, user type is invalid.
        /// </summary>
        public static string errorUserTypeInvalid {
            get {
                return ResourceManager.GetString("errorUserTypeInvalid", resourceCulture);
            }
        }
    }
}
