// <auto-generated />
using System;
using App.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Shared.Models.AdditionsModules.Shared.Colors.Color", b =>
                {
                    b.Property<int>("colorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("colorId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("colorDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorHexCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("colorId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("App.Shared.Models.AdditionsModules.Shared.Units.Unit", b =>
                {
                    b.Property<int>("unitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unitId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("unitDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unitSympol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("unitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("App.Shared.Models.Buyers.UserClient", b =>
                {
                    b.Property<int>("userClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userClientId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("userClientId");

                    b.ToTable("UserClient");
                });

            modelBuilder.Entity("App.Shared.Models.Buyers.UserProfile", b =>
                {
                    b.Property<int>("userProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userProfileId"));

                    b.Property<DateOnly>("buyerBirthDate")
                        .HasColumnType("date");

                    b.Property<string>("userContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCCName_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCCName_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCCName_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCC_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCC_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCC_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhone_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhone_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhone_4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userProfileId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("App.Shared.Models.PlacesModules.Branches.Branch", b =>
                {
                    b.Property<int>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("branchId"));

                    b.Property<TimeSpan>("branchCloseAt")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("branchOpenAt")
                        .HasColumnType("time");

                    b.HasKey("branchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("App.Shared.Models.PlacesModules.Stores.Store", b =>
                {
                    b.Property<int>("storeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("storeId"));

                    b.Property<TimeSpan>("storeCloseAt")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("storeOpenAt")
                        .HasColumnType("time");

                    b.HasKey("storeId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("App.Shared.Models.ProductStores.ProductStore", b =>
                {
                    b.Property<int>("productStoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productStoreId"));

                    b.Property<int>("colorId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("unitId")
                        .HasColumnType("int");

                    b.HasKey("productStoreId");

                    b.HasIndex("colorId");

                    b.HasIndex("productId");

                    b.HasIndex("unitId");

                    b.ToTable("ProductStores");
                });

            modelBuilder.Entity("App.Shared.Models.Products.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<int?>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("productDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("App.Shared.Models.ProductsModules.Categories.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("App.Shared.Models.SystemBase.Roles.SystemRole", b =>
                {
                    b.Property<int>("systemRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("systemRoleId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("systemRoleCanUseDefault")
                        .HasColumnType("bit");

                    b.Property<string>("systemRoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("systemRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("systemRoleUserType")
                        .HasColumnType("int");

                    b.HasKey("systemRoleId");

                    b.ToTable("SystemRoles");
                });

            modelBuilder.Entity("App.Shared.Models.Users.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("systemRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("userBuyerDatauserClientId")
                        .HasColumnType("int");

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userLoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPhoneCCName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("userProfileId")
                        .HasColumnType("int");

                    b.Property<int>("userType")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("systemRoleId");

                    b.HasIndex("userBuyerDatauserClientId");

                    b.HasIndex("userProfileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("App.Shared.Models.UsersModule.LogActionsModel.LogAction", b =>
                {
                    b.Property<int>("logActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logActionId"));

                    b.Property<DateTimeOffset>("actionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("actionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("logActionId");

                    b.ToTable("LogActions");
                });

            modelBuilder.Entity("App.Shared.Models.PlacesModules.Branches.Branch", b =>
                {
                    b.OwnsOne("App.Shared.Models.PlacesModules.Branches.BranchContactInfo", "branchContactInfo", b1 =>
                        {
                            b1.Property<int>("branchId")
                                .HasColumnType("int");

                            b1.Property<string>("branchAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("branchCountryCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("branchCountryCodeName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("branchDailCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("branchEmail")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("branchLatitude")
                                .HasColumnType("float");

                            b1.Property<double>("branchLongitude")
                                .HasColumnType("float");

                            b1.Property<string>("branchManagerName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("branchName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("branchPhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("jsutForBuildEF")
                                .HasColumnType("bit");

                            b1.HasKey("branchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("branchId");
                        });

                    b.OwnsOne("App.Shared.Models.PlacesModules.Branches.BranchContactSocialMedia", "branchContactSocialMedia", b1 =>
                        {
                            b1.Property<int>("branchId")
                                .HasColumnType("int");

                            b1.Property<string>("branchWebsite")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("facebookLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("instagramLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("jsutForBuildEF")
                                .HasColumnType("bit");

                            b1.Property<string>("linkedinLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("twitterLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("youtubeLink")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("branchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("branchId");
                        });

                    b.Navigation("branchContactInfo");

                    b.Navigation("branchContactSocialMedia");
                });

            modelBuilder.Entity("App.Shared.Models.PlacesModules.Stores.Store", b =>
                {
                    b.OwnsOne("App.Shared.Models.PlacesModules.Stores.StoreContactInfo", "storeContactInfo", b1 =>
                        {
                            b1.Property<int>("storeId")
                                .HasColumnType("int");

                            b1.Property<bool>("jsutForBuildEF")
                                .HasColumnType("bit");

                            b1.Property<string>("storeAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("storeCountryCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("storeCountryCodeName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("storeDailCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("storeEmail")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("storeLatitude")
                                .HasColumnType("float");

                            b1.Property<double>("storeLongitude")
                                .HasColumnType("float");

                            b1.Property<string>("storeManagerName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("storeName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("storePhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("storeId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("storeId");
                        });

                    b.OwnsOne("App.Shared.Models.PlacesModules.Stores.StoreContactSocialMedia", "storeContactSocialMedia", b1 =>
                        {
                            b1.Property<int>("storeId")
                                .HasColumnType("int");

                            b1.Property<string>("facebookLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("instagramLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("jsutForBuildEF")
                                .HasColumnType("bit");

                            b1.Property<string>("linkedinLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("storeWebsite")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("twitterLink")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("youtubeLink")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("storeId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("storeId");
                        });

                    b.Navigation("storeContactInfo");

                    b.Navigation("storeContactSocialMedia");
                });

            modelBuilder.Entity("App.Shared.Models.ProductStores.ProductStore", b =>
                {
                    b.HasOne("App.Shared.Models.AdditionsModules.Shared.Colors.Color", "colorData")
                        .WithMany("productStoreData")
                        .HasForeignKey("colorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Shared.Models.Products.Product", "productData")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Shared.Models.AdditionsModules.Shared.Units.Unit", "unitData")
                        .WithMany("productStoresData")
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("colorData");

                    b.Navigation("productData");

                    b.Navigation("unitData");
                });

            modelBuilder.Entity("App.Shared.Models.Products.Product", b =>
                {
                    b.HasOne("App.Shared.Models.ProductsModules.Categories.Category", null)
                        .WithMany("productsData")
                        .HasForeignKey("categoryId");
                });

            modelBuilder.Entity("App.Shared.Models.Users.User", b =>
                {
                    b.HasOne("App.Shared.Models.SystemBase.Roles.SystemRole", "roleData")
                        .WithMany("usersData")
                        .HasForeignKey("systemRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Shared.Models.Buyers.UserClient", "userBuyerData")
                        .WithMany()
                        .HasForeignKey("userBuyerDatauserClientId");

                    b.HasOne("App.Shared.Models.Buyers.UserProfile", "userProfile")
                        .WithMany()
                        .HasForeignKey("userProfileId");

                    b.Navigation("roleData");

                    b.Navigation("userBuyerData");

                    b.Navigation("userProfile");
                });

            modelBuilder.Entity("App.Shared.Models.AdditionsModules.Shared.Colors.Color", b =>
                {
                    b.Navigation("productStoreData");
                });

            modelBuilder.Entity("App.Shared.Models.AdditionsModules.Shared.Units.Unit", b =>
                {
                    b.Navigation("productStoresData");
                });

            modelBuilder.Entity("App.Shared.Models.ProductsModules.Categories.Category", b =>
                {
                    b.Navigation("productsData");
                });

            modelBuilder.Entity("App.Shared.Models.SystemBase.Roles.SystemRole", b =>
                {
                    b.Navigation("usersData");
                });
#pragma warning restore 612, 618
        }
    }
}
